---
kind: SeldonDeployment
apiVersion: machinelearning.seldon.io/v1alpha2
metadata:
  name: iris-test
  namespace: gitops-namespace
  creationTimestamp:
  labels:
    fluentd: 'true'
spec:
  name: iris-test
  predictors:
  - name: default
    graph:
      name: iris-test-container
      type: MODEL
      implementation: SKLEARN_SERVER
      endpoint:
        service_host: localhost
        service_port: 9000
        type: REST
      modelUri: gs://seldon-models/sklearn/iris
      logger:
        mode: all
    componentSpecs:
    - metadata:
        creationTimestamp: '2020-09-30T09:18:26Z'
      spec:
        containers:
        - name: iris-test-container
          image: seldonio/sklearnserver_rest:1.3.0
          ports:
          - name: metrics
            containerPort: 6000
            protocol: TCP
          resources: {}
          volumeMounts:
          - name: seldon-podinfo
            mountPath: "/etc/podinfo"
    replicas: 1
    engineResources: {}
    labels:
      version: default
    svcOrchSpec: {}
    traffic: 90
  - name: canary
    graph:
      name: iris-test-container
      implementation: SKLEARN_SERVER
      endpoint:
        type: REST
      modelUri: gs://seldon-models/sklearn/iris
      logger:
        mode: all
    componentSpecs:
    - metadata:
        creationTimestamp: '2020-09-30T09:36:49Z'
      spec:
        containers:
        - name: iris-test-container
          resources: {}
    replicas: 1
    annotations:
      seldon.io/canary: 'true'
    engineResources: {}
    svcOrchSpec: {}
    traffic: 10
  annotations:
    seldon.io/engine-seldon-log-messages-externally: 'true'
  protocol: seldon
  transport: rest
status: {}
