apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  selector:
    matchLabels:
      app: echo-server
  replicas: 3
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: server
        image: rafalskolasinski/echo-server:latest

---

apiVersion: v1
kind: Service
metadata:
  name: echo-server
  labels:
    app: echo-server
spec:
  type: NodePort
  # type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: echo-server
